# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    fos_user.doctrine_registry:
        alias: doctrine

    redirect.after.login:
        class: Home\UserBundle\Redirection\AfterLoginRedirection
        arguments: ['@router','@security.authorization_checker']

    redirect.after.logout:
        class: Home\UserBundle\Redirection\AfterLogoutRedirection
        arguments: ['@router']

    app.form.registration:
        class: Home\UserBundle\Form\UserType
        tags:
            - { name: form.type, alias: app_user_registration }
