<?php

namespace Home\FavorisBundle\Repository;

/**
 * MessageURepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageURepository extends \Doctrine\ORM\EntityRepository
{
}
