<?php

namespace Home\FavorisBundle\Repository;

/**
 * PostUserLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostUserLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
