<?php

namespace Home\FavorisBundle\Repository;

/**
 * PostUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostUserRepository extends \Doctrine\ORM\EntityRepository
{
}
