<?php

namespace Home\EntityBundle\Repository;

/**
 * MailAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
